name: Automated Workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python and Jupyter
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python -m pip install --upgrade pip
      - run: python -m pip install jupyter

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run code
        run: jupyter nbconvert --to notebook --execute your_notebook.ipynb
